# Dependencies
highlighter:      rouge
markdown:         kramdown
kramdown:
  input: GFM

# Permalinks
permalink:        pretty

# Setup
title:            Lucas Fern  
tagline:          '🧙'
description:      'Student'
url:              http://lucas-fern.github.io
baseurl:          ""

author:
  name:           'Lucas Fern'
  url:            https://github.com/lucas-fern

#gems:             [jekyll-paginate]
plugins: [jekyll-paginate]
paginate:         5

# Custom vars
#version:          2.1.0
comments:         true

github:
  repo:           https://github.com/poole/hyde
